DROP TABLE IF EXISTS fortune;

CREATE TABLE fortune (
  id     INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  kind   ENUM('memory', 'wish') NOT NULL,
  body   TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  opened BOOLEAN NOT NULL DEFAULT FALSE
);
